export type DRECategoria = {
  id: string;
  label: string;
  nivel: number; // 0 = totalizador, 1 = grupo, 2 = subgrupo, 3 = item
  tipo: "receita" | "deducao" | "custo" | "despesa" | "resultado";
  cor?: string;
  negrito?: boolean;
  valores: number[];
};

export const meses = ["MAR/25", "ABR/25", "MAI/25", "JUN/25", "JUL/25", "AGO/25", "SET/25", "OUT/25"];

const Z = [0, 0, 0, 0, 0, 0, 0, 0];

export const dreCategorias: DRECategoria[] = [
  // 1 - RECEITA BRUTA DE VENDA
  { id: "1", label: "(+) RECEITA BRUTA DE VENDA", nivel: 1, tipo: "receita", cor: "bg-green-50 border-l-4 border-l-green-500", negrito: true, valores: [...Z] },
  { id: "1.1", label: "(+) VENDA BALCÃO", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "1.2", label: "(+) VENDA ORDEM DE SERVIÇO", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "1.3", label: "(+) VENDA ATACADO", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "1.4", label: "(+) VENDA E-COMMERCE", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "1.5", label: "(+) VENDA MARKETPLACES", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "1T", label: "(=) RECEITA BRUTA DE VENDA TOTAL", nivel: 0, tipo: "receita", cor: "bg-green-100 font-bold", negrito: true, valores: [...Z] },

  // CMV
  { id: "CMV", label: "(-) CMV - CUSTO MERCADORIA VENDIDA", nivel: 1, tipo: "custo", cor: "bg-red-50 border-l-4 border-l-red-400", negrito: true, valores: [...Z] },
  { id: "CMV.1", label: "(-) CUSTO MERCADORIA", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "CMVT", label: "(=) RECEITA LÍQUIDA", nivel: 0, tipo: "resultado", cor: "bg-blue-50 font-bold", negrito: true, valores: [...Z] },

  // 2 - RECEITA SERVIÇOS TERCEIRIZADOS
  { id: "2", label: "(+) RECEITA SERVIÇOS TERCEIRIZADOS", nivel: 1, tipo: "receita", cor: "bg-green-50 border-l-4 border-l-green-400", negrito: true, valores: [...Z] },
  { id: "2.1", label: "(+) SERVIÇOS TERCEIRIZADOS", nivel: 3, tipo: "receita", valores: [...Z] },

  // 3 - OUTRAS RECEITAS OPERACIONAIS
  { id: "3", label: "(+) OUTRAS RECEITAS OPERACIONAIS", nivel: 1, tipo: "receita", cor: "bg-green-50 border-l-4 border-l-green-400", negrito: true, valores: [...Z] },
  { id: "3.01", label: "OUTRAS RECEITAS", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "3.02", label: "RECEITA DE SERVIÇO TERCEIRIZADOS", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "3.03", label: "ACRÉSCIMOS", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "3T", label: "(=) LUCRO BRUTO", nivel: 0, tipo: "resultado", cor: "bg-emerald-100 font-bold text-emerald-800", negrito: true, valores: [...Z] },

  // 4 - CUSTOS VARIÁVEIS
  { id: "4", label: "(-) CUSTOS VARIÁVEIS", nivel: 1, tipo: "custo", cor: "bg-red-50 border-l-4 border-l-red-500", negrito: true, valores: [...Z] },
  { id: "4.1", label: "(-) IMPOSTOS", nivel: 2, tipo: "custo", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "4.1.1", label: "ICMS S/ VENDAS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.1.2", label: "IPI S/ VENDAS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.1.3", label: "PIS S/ VENDAS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.1.4", label: "COFINS S/ VENDAS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.1.6", label: "ENCARGOS FOLHA - FGTS / RECEITA ARRECADAÇÃO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.1.7", label: "IRPJ", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.2", label: "(-) CUSTOS FINANCEIROS", nivel: 2, tipo: "custo", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "4.2.1", label: "TAXA DE BOLETO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.2.2", label: "TAXA CARTÃO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3", label: "(-) CUSTO COM TRANSPORTE", nivel: 2, tipo: "custo", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "4.3.1", label: "FRETES E CARRETOS OUTROS SERVIÇO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.2", label: "DESPESA C/ COMBUSTÍVEIS VEÍCULOS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.3", label: "DESPESA C/ COMBUSTÍVEIS GERADOR", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.4", label: "DESPESAS C/ LUBRIFICANTES", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.5", label: "DESPESA C/ SERVIÇOS DE MANUTENÇÃO E CONSERVAÇÃO DE VEÍCULOS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.6", label: "DESPESA C/ PEÇAS DE MANUTENÇÃO E CONSERVAÇÃO DE VEÍCULOS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.7", label: "MULTAS DE TRÂNSITO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.8", label: "IPVA, DPVAT E LICENCIAMENTO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.9", label: "PEDÁGIO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.10", label: "ALIMENTAÇÃO TRANSPORTE (MOTORISTAS/CARREGADORES)", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.12", label: "FRETE - DIÁRIA DE VEÍCULOS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.3.13", label: "SEGURO VEÍCULO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5", label: "(-) CUSTO COM MARKETING E COMERCIAL", nivel: 2, tipo: "custo", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "4.5.1", label: "COMISSÃO SOBRE A VENDA", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.2", label: "DESPESAS C/ BONIFICAÇÃO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.3", label: "EMPRESA DE MKT", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.4", label: "SOCIAL MÍDIAS E DESIGNER", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.5", label: "PANFLETAGEM", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.6", label: "PUBLICIDADE E PROPAGANDA", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.7", label: "MKT PATROCINADO (TRÁFEGO)", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.8", label: "DESP. C/ TX MENSALIDADES/ANUIDADE", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.9", label: "FEIRAS E EVENTOS - MKT", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.10", label: "PAPELARIA (FOLDER, CARTÃO VISITAS, ETC.)", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.11", label: "SITE / INTERNET", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.12", label: "PRESTADORES DE SERVIÇOS DE MARKETING", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.13", label: "OUTROS INVESTIMENTOS EM MARKETING", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.5.14", label: "BRINDES E PATROCÍNIO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.6", label: "(-) CUSTOS DIRETO OPERACIONAL", nivel: 2, tipo: "custo", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "4.6.1", label: "ETIQUETAS E LACRE", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.6.2", label: "EMBALAGENS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.6.3", label: "PRODUTOS QUÍMICOS", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.6.4", label: "TERCEIRIZAÇÃO DE BALANÇA", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4.6.5", label: "VETERINÁRIO", nivel: 3, tipo: "custo", valores: [...Z] },
  { id: "4T", label: "(=) MARGEM DE CONTRIBUIÇÃO", nivel: 0, tipo: "resultado", cor: "bg-yellow-100 font-bold", negrito: true, valores: [...Z] },

  // 5 - DESPESAS FIXAS
  { id: "5", label: "(-) DESPESAS FIXAS", nivel: 1, tipo: "despesa", cor: "bg-red-50 border-l-4 border-l-red-500", negrito: true, valores: [...Z] },
  { id: "5.1", label: "(-) PRÓ-LABORE SÓCIOS", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "5.1.1", label: "PRÓ-LABORE SÓCIO 1", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.1.4", label: "PRÓ-LABORE SÓCIOS 2", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.1.5", label: "INSS - PRÓ-LABORE", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2", label: "(-) DESPESAS COM PESSOAL", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "5.2.1", label: "SALÁRIOS OPERACIONAL", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.2", label: "SALÁRIOS ADMINISTRATIVO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.3", label: "JOVEM APRENDIZ E ESTAGIÁRIOS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.4", label: "COMISSÕES S/ VENDAS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.5", label: "13º SALÁRIO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.6", label: "FÉRIAS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.7", label: "RESCISÕES", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.8", label: "VALE TRANSPORTE", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.9", label: "ALMOÇO / LANCHE / MERCADO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.10", label: "INSS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.11", label: "FGTS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.12", label: "INSS S/ FÉRIAS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.13", label: "INSS S/ 13 SALÁRIO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.14", label: "FGTS S/ FÉRIAS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.15", label: "FGTS S/ 13 SALÁRIO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.16", label: "FGTS MULTA RESCISÓRIA", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.17", label: "GRATIFICAÇÕES DIVERSAS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.18", label: "ASSISTÊNCIA MÉDICA E EXAME PERIÓDICO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.19", label: "SINDICATOS E ASSOCIAÇÕES DE CLASSE", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.20", label: "ASSISTÊNCIA SOCIAL/CONFRATERNIZAÇÕES", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.21", label: "AJUDA DE CUSTO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.22", label: "CURSOS/TREINAMENTOS/CONGRESSOS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.23", label: "SISTEMA DE PONTO ELETRÔNICO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.24", label: "ABONO PECUNIÁRIO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.25", label: "INCENTIVO A PRODUTIVIDADE (BÔNUS)", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.26", label: "FARDAMENTOS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.27", label: "EPI - EQUIPAMENTO PROTEÇÃO INDIVIDUAL", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.2.28", label: "DIÁRIA DE PROFISSIONAL", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.3", label: "(-) DESPESAS COM CONTAS DE CONSUMO E IMÓVEIS", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "5.3.1", label: "TELEFONE E INTERNET", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.3.2", label: "CELULAR", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.3.3", label: "ENERGIA ELÉTRICA", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.3.4", label: "EMBASA", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.3.5", label: "IPTU", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.4", label: "(-) DESPESAS COM TERCEIRIZADOS", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "5.4.1", label: "CONTABILIDADE", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.4.2", label: "ADVOGADO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.4.3", label: "CONSULTORIA", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.4.4", label: "SISTEMA", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.4.5", label: "SUPORTE T.I.", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.5", label: "(-) DESPESAS COM MANUTENÇÃO", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "5.5.1", label: "MATERIAIS DE LIMPEZA", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.5.2", label: "DEDETIZAÇÃO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.5.3", label: "MANUTENÇÃO PREDIAL", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.5.4", label: "MANUTENÇÃO EQUIPAMENTOS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.6", label: "(-) DESPESAS ADMINISTRATIVAS", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "5.6.1", label: "TARIFAS BANCÁRIAS (BB)", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.6.2", label: "TARIFAS BANCÁRIAS (CAIXA)", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.6.3", label: "TAXAS PATRONAIS/TFF", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.6.4", label: "DESPESAS VEÍCULO ADM", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.6.5", label: "DESPESAS COMBUSTÍVEL ADM", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.6.6", label: "MATERIAL ESCRITÓRIO E EXPEDIENTE", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5.6.7", label: "JUROS FORNECEDORES", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "5T", label: "(=) RESULTADO OPERACIONAL", nivel: 0, tipo: "resultado", cor: "bg-blue-100 font-bold", negrito: true, valores: [...Z] },

  // 6 - RECEITAS NÃO OPERACIONAIS
  { id: "6", label: "(+) RECEITAS NÃO OPERACIONAIS", nivel: 1, tipo: "receita", cor: "bg-green-50 border-l-4 border-l-green-300", negrito: true, valores: [...Z] },
  { id: "6.1", label: "(+) EMPRÉSTIMOS E APORTES", nivel: 2, tipo: "receita", cor: "bg-green-50/50", negrito: true, valores: [...Z] },
  { id: "6.1.1", label: "EMPRÉSTIMOS BANCÁRIOS", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "6.1.2", label: "APORTES SÓCIOS", nivel: 3, tipo: "receita", valores: [...Z] },
  { id: "6.1.3", label: "CONSÓRCIOS", nivel: 3, tipo: "receita", valores: [...Z] },

  // 7 - DESPESAS NÃO OPERACIONAIS
  { id: "7", label: "(-) DESPESAS NÃO OPERACIONAIS", nivel: 1, tipo: "despesa", cor: "bg-red-50 border-l-4 border-l-red-300", negrito: true, valores: [...Z] },
  { id: "7.1", label: "(-) BANCOS (EMPRÉSTIMOS)", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "7.1.1", label: "BANCOS BB (EMPRÉSTIMOS)", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.1.2", label: "BANCOS CAIXA (EMPRÉSTIMOS)", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.2", label: "(-) BANCOS (CONSÓRCIOS)", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "7.2.1", label: "CONSÓRCIO - VEÍCULO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.2.2", label: "CONSÓRCIO - IMÓVEL", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.2.3", label: "CONSÓRCIO - ENERGIA SOLAR", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.2.4", label: "FINANCIAMENTO - VEÍCULO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.3", label: "(-) INVESTIMENTOS", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "7.3.1", label: "MÓVEIS E EQUIPAMENTOS", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.3.2", label: "VEÍCULO", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.4", label: "(-) DESPESAS SÓCIO", nivel: 2, tipo: "despesa", cor: "bg-red-50/50", negrito: true, valores: [...Z] },
  { id: "7.4.1", label: "DESPESAS FAZENDA", nivel: 3, tipo: "despesa", valores: [...Z] },
  { id: "7.4.2", label: "DESPESAS PESSOAL", nivel: 3, tipo: "despesa", valores: [...Z] },

  // RESULTADO LÍQUIDO
  { id: "7T", label: "(=) RESULTADO LÍQUIDO", nivel: 0, tipo: "resultado", cor: "bg-emerald-200 font-bold text-emerald-900", negrito: true, valores: [...Z] },
];
