export interface Tarefa {
  id: string;
  texto: string;
}

export interface Setor {
  id: string;
  nome: string;
  descricao: string;
  icon: string;
  tarefas: Tarefa[];
}

export const setores: Setor[] = [
  {
    id: "mecanico",
    nome: "Mecânico",
    descricao: "Manutenção e reparos de motos",
    icon: "Wrench",
    tarefas: [
      { id: "m1", texto: "Verificar ordens de serviço pendentes" },
      { id: "m2", texto: "Conferir disponibilidade de peças para OS do dia" },
      { id: "m3", texto: "Realizar diagnóstico dos veículos agendados" },
      { id: "m4", texto: "Executar serviços conforme ordem de prioridade" },
      { id: "m5", texto: "Registrar peças utilizadas em cada OS" },
      { id: "m6", texto: "Atualizar status das OS em andamento" },
      { id: "m7", texto: "Informar ao atendente sobre conclusão de serviços" },
      { id: "m8", texto: "Solicitar peças em falta ao estoquista" },
      { id: "m9", texto: "Realizar teste final após conclusão do serviço" },
      { id: "m10", texto: "Manter área de trabalho organizada e limpa" },
      { id: "m11", texto: "Registrar horas trabalhadas por OS" },
      { id: "m12", texto: "Verificar ferramentas e equipamentos" },
      { id: "m13", texto: "Reportar problemas adicionais encontrados" },
      { id: "m14", texto: "Seguir procedimentos de segurança" },
      { id: "m15", texto: "Documentar serviços realizados com fotos" },
      { id: "m16", texto: "Calibrar equipamentos de medição" },
      { id: "m17", texto: "Verificar estoque de consumíveis (óleo, filtros)" },
      { id: "m18", texto: "Participar de treinamentos técnicos" },
      { id: "m19", texto: "Fazer limpeza da bancada ao final do turno" },
    ],
  },
  {
    id: "vendedor-loja",
    nome: "Vendedor da Loja",
    descricao: "Atendimento e vendas presenciais",
    icon: "ShoppingCart",
    tarefas: [
      { id: "vl1", texto: "Abrir a loja e verificar a exposição dos produtos" },
      { id: "vl2", texto: "Conferir promoções e etiquetas de preço" },
      { id: "vl3", texto: "Atender clientes com excelência" },
      { id: "vl4", texto: "Registrar vendas no sistema PDV" },
      { id: "vl5", texto: "Oferecer produtos complementares (cross-sell)" },
      { id: "vl6", texto: "Consultar disponibilidade de estoque" },
      { id: "vl7", texto: "Emitir notas e cupons fiscais" },
      { id: "vl8", texto: "Organizar vitrine e prateleiras" },
      { id: "vl9", texto: "Fazer follow-up com clientes de orçamentos" },
      { id: "vl10", texto: "Cadastrar novos clientes no sistema" },
      { id: "vl11", texto: "Informar clientes sobre promoções vigentes" },
      { id: "vl12", texto: "Separar produtos para entrega/retirada" },
      { id: "vl13", texto: "Solicitar reposição de produtos na prateleira" },
      { id: "vl14", texto: "Registrar trocas e devoluções" },
      { id: "vl15", texto: "Manter área de vendas organizada" },
      { id: "vl16", texto: "Verificar metas diárias de vendas" },
      { id: "vl17", texto: "Reportar produtos com defeito" },
      { id: "vl18", texto: "Fechar caixa ao final do turno" },
    ],
  },
  {
    id: "atendente-oficina",
    nome: "Atendente da Oficina",
    descricao: "Atendimento e coordenação de serviços",
    icon: "Headphones",
    tarefas: [
      { id: "ao1", texto: "Recepcionar clientes e veículos" },
      { id: "ao2", texto: "Abrir ordens de serviço" },
      { id: "ao3", texto: "Realizar checklist de entrada do veículo" },
      { id: "ao4", texto: "Informar prazos estimados ao cliente" },
      { id: "ao5", texto: "Acompanhar andamento das OS com mecânicos" },
      { id: "ao6", texto: "Comunicar cliente sobre aprovação de serviços" },
      { id: "ao7", texto: "Agendar serviços e retornos" },
      { id: "ao8", texto: "Registrar reclamações e sugestões" },
      { id: "ao9", texto: "Solicitar aprovação de orçamentos ao cliente" },
      { id: "ao10", texto: "Realizar checkout e entrega do veículo" },
      { id: "ao11", texto: "Enviar mensagens de acompanhamento via WhatsApp" },
      { id: "ao12", texto: "Organizar fila de atendimento" },
      { id: "ao13", texto: "Verificar agenda de serviços do dia" },
      { id: "ao14", texto: "Confirmar agendamentos do dia seguinte" },
      { id: "ao15", texto: "Atualizar cadastro de clientes" },
      { id: "ao16", texto: "Tirar fotos do veículo na entrada" },
      { id: "ao17", texto: "Verificar histórico do cliente/veículo" },
      { id: "ao18", texto: "Cobrar aprovação de orçamentos pendentes" },
      { id: "ao19", texto: "Registrar pesquisa de satisfação" },
    ],
  },
  {
    id: "estoquista",
    nome: "Estoquista",
    descricao: "Controle e organização do estoque",
    icon: "Package",
    tarefas: [
      { id: "e1", texto: "Conferir entregas de fornecedores" },
      { id: "e2", texto: "Registrar entradas no sistema" },
      { id: "e3", texto: "Organizar produtos por categoria/localização" },
      { id: "e4", texto: "Separar peças para ordens de serviço" },
      { id: "e5", texto: "Verificar produtos com estoque mínimo" },
      { id: "e6", texto: "Solicitar reposição de produtos em falta" },
      { id: "e7", texto: "Realizar contagem de inventário periódica" },
      { id: "e8", texto: "Etiquetar produtos novos" },
      { id: "e9", texto: "Conferir validade de produtos" },
      { id: "e10", texto: "Registrar transferências entre setores" },
      { id: "e11", texto: "Manter depósito organizado e limpo" },
      { id: "e12", texto: "Devolver peças não utilizadas ao estoque" },
      { id: "e13", texto: "Reportar avarias e extravios" },
      { id: "e14", texto: "Embalar produtos para envio" },
      { id: "e15", texto: "Atualizar localização de produtos" },
    ],
  },
  {
    id: "vendedor-ecommerce",
    nome: "Vendedor E-commerce",
    descricao: "Vendas online e atendimento digital",
    icon: "Monitor",
    tarefas: [
      { id: "ve1", texto: "Verificar novos pedidos nos marketplaces" },
      { id: "ve2", texto: "Responder perguntas de clientes online" },
      { id: "ve3", texto: "Atualizar anúncios e descrições de produtos" },
      { id: "ve4", texto: "Separar e embalar pedidos para envio" },
      { id: "ve5", texto: "Gerar etiquetas de envio" },
      { id: "ve6", texto: "Postar envios na transportadora/Correios" },
      { id: "ve7", texto: "Acompanhar entregas e rastreamentos" },
      { id: "ve8", texto: "Resolver problemas de envio e devoluções" },
      { id: "ve9", texto: "Cadastrar novos produtos nos marketplaces" },
      { id: "ve10", texto: "Atualizar preços e promoções online" },
      { id: "ve11", texto: "Monitorar avaliações e reputação" },
      { id: "ve12", texto: "Criar campanhas promocionais" },
      { id: "ve13", texto: "Analisar métricas de vendas online" },
      { id: "ve14", texto: "Fotografar produtos para anúncios" },
      { id: "ve15", texto: "Sincronizar estoque entre canais" },
      { id: "ve16", texto: "Atender reclamações e devoluções" },
      { id: "ve17", texto: "Gerenciar anúncios pagos" },
      { id: "ve18", texto: "Verificar concorrência e preços" },
      { id: "ve19", texto: "Atualizar vitrines dos marketplaces" },
      { id: "ve20", texto: "Processar cancelamentos" },
      { id: "ve21", texto: "Verificar métricas de performance" },
      { id: "ve22", texto: "Enviar mensagens pós-venda" },
      { id: "ve23", texto: "Fazer backup de fotos e anúncios" },
    ],
  },
  {
    id: "caixa",
    nome: "Caixa",
    descricao: "Controle financeiro e pagamentos",
    icon: "DollarSign",
    tarefas: [
      { id: "cx1", texto: "Abrir o caixa com conferência de troco" },
      { id: "cx2", texto: "Registrar todas as vendas e recebimentos" },
      { id: "cx3", texto: "Processar pagamentos (cartão, dinheiro, PIX)" },
      { id: "cx4", texto: "Emitir notas fiscais e cupons" },
      { id: "cx5", texto: "Registrar sangrias e suprimentos" },
      { id: "cx6", texto: "Receber pagamentos de OS finalizadas" },
      { id: "cx7", texto: "Conferir valores de recebimentos" },
      { id: "cx8", texto: "Registrar pagamentos parcelados" },
      { id: "cx9", texto: "Lançar contas a pagar do dia" },
      { id: "cx10", texto: "Processar devoluções e estornos" },
      { id: "cx11", texto: "Conferir comprovantes de cartão" },
      { id: "cx12", texto: "Organizar documentos fiscais" },
      { id: "cx13", texto: "Realizar sangria quando necessário" },
      { id: "cx14", texto: "Conferir troco e numerário" },
      { id: "cx15", texto: "Fechar o caixa com relatório detalhado" },
      { id: "cx16", texto: "Verificar divergências de valores" },
      { id: "cx17", texto: "Depositar valores em conta bancária" },
    ],
  },
  {
    id: "financeiro",
    nome: "Setor Financeiro",
    descricao: "Gestão financeira e pagamentos",
    icon: "Calculator",
    tarefas: [
      { id: "f1", texto: "Verificar contas a pagar do dia" },
      { id: "f2", texto: "Verificar contas a receber vencidas" },
      { id: "f3", texto: "Realizar conciliação bancária" },
      { id: "f4", texto: "Emitir boletos e cobranças" },
      { id: "f5", texto: "Verificar fluxo de caixa projetado" },
      { id: "f6", texto: "Analisar DRE do período" },
      { id: "f7", texto: "Processar pagamentos a fornecedores" },
      { id: "f8", texto: "Calcular comissões de vendedores" },
      { id: "f9", texto: "Gerar relatórios financeiros" },
    ],
  },
  {
    id: "administracao",
    nome: "Administração",
    descricao: "Gestão administrativa geral",
    icon: "Building",
    tarefas: [
      { id: "a1", texto: "Verificar indicadores do dashboard" },
      { id: "a2", texto: "Analisar relatórios de vendas" },
      { id: "a3", texto: "Verificar satisfação dos clientes" },
      { id: "a4", texto: "Revisar metas da equipe" },
      { id: "a5", texto: "Autorizar compras e pagamentos" },
      { id: "a6", texto: "Verificar agenda de compromissos" },
      { id: "a7", texto: "Analisar performance dos setores" },
      { id: "a8", texto: "Resolver pendências administrativas" },
      { id: "a9", texto: "Verificar compliance e documentação" },
      { id: "a10", texto: "Planejar ações de marketing" },
      { id: "a11", texto: "Avaliar necessidade de contratações" },
      { id: "a12", texto: "Verificar contratos vigentes" },
    ],
  },
  {
    id: "compras",
    nome: "Setor de Compras",
    descricao: "Compras e relacionamento com fornecedores",
    icon: "ShoppingBag",
    tarefas: [
      { id: "co1", texto: "Verificar solicitações de compra pendentes" },
      { id: "co2", texto: "Cotar preços com fornecedores" },
      { id: "co3", texto: "Analisar cotações recebidas" },
      { id: "co4", texto: "Emitir pedidos de compra" },
      { id: "co5", texto: "Acompanhar entregas pendentes" },
      { id: "co6", texto: "Avaliar fornecedores" },
      { id: "co7", texto: "Negociar prazos e condições" },
    ],
  },
  {
    id: "gerente",
    nome: "Gerente",
    descricao: "Gestão geral e resolução de problemas",
    icon: "Crown",
    tarefas: [
      { id: "g1", texto: "Verificar metas diárias da equipe" },
      { id: "g2", texto: "Acompanhar OS críticas e atrasadas" },
      { id: "g3", texto: "Verificar satisfação dos clientes" },
      { id: "g4", texto: "Resolver conflitos e problemas operacionais" },
      { id: "g5", texto: "Analisar indicadores de performance" },
      { id: "g6", texto: "Verificar escalas e presenças" },
      { id: "g7", texto: "Aprovar orçamentos acima do limite" },
      { id: "g8", texto: "Realizar reunião rápida com a equipe" },
      { id: "g9", texto: "Verificar estoque de produtos críticos" },
      { id: "g10", texto: "Acompanhar faturamento do dia" },
      { id: "g11", texto: "Verificar reclamações pendentes" },
      { id: "g12", texto: "Planejar ações do dia seguinte" },
      { id: "g13", texto: "Avaliar necessidade de horas extras" },
    ],
  },
  {
    id: "gestao-oficina",
    nome: "Gestão da Oficina",
    descricao: "Normas e procedimentos da oficina",
    icon: "Settings",
    tarefas: [
      { id: "go1", texto: "Verificar limpeza e organização da oficina" },
      { id: "go2", texto: "Conferir equipamentos de segurança (EPIs)" },
      { id: "go3", texto: "Verificar funcionamento das ferramentas" },
      { id: "go4", texto: "Checar iluminação e ventilação" },
      { id: "go5", texto: "Verificar descarte correto de resíduos" },
      { id: "go6", texto: "Conferir extintores e saídas de emergência" },
      { id: "go7", texto: "Verificar estoque de consumíveis da oficina" },
      { id: "go8", texto: "Acompanhar produtividade dos mecânicos" },
      { id: "go9", texto: "Verificar qualidade dos serviços realizados" },
      { id: "go10", texto: "Registrar manutenção de equipamentos" },
      { id: "go11", texto: "Verificar cumprimento de prazos" },
      { id: "go12", texto: "Aplicar checklist de encerramento do dia" },
      { id: "go13", texto: "Conferir se todas as OS foram atualizadas" },
      { id: "go14", texto: "Registrar ocorrências do dia" },
      { id: "go15", texto: "Verificar necessidade de treinamentos" },
      { id: "go16", texto: "Conferir agenda do dia seguinte" },
      { id: "go17", texto: "Verificar laudos técnicos pendentes" },
      { id: "go18", texto: "Auditar uso de peças e materiais" },
      { id: "go19", texto: "Verificar calibração de equipamentos" },
      { id: "go20", texto: "Avaliar indicadores de retrabalho" },
      { id: "go21", texto: "Monitorar tempo médio de serviço" },
      { id: "go22", texto: "Verificar conformidade com normas técnicas" },
    ],
  },
  {
    id: "gestao-loja",
    nome: "Gestão da Loja",
    descricao: "Normas e procedimentos da loja",
    icon: "Store",
    tarefas: [
      { id: "gl1", texto: "Verificar abertura e fechamento da loja" },
      { id: "gl2", texto: "Conferir vitrine e exposição de produtos" },
      { id: "gl3", texto: "Verificar preços e etiquetas" },
      { id: "gl4", texto: "Monitorar atendimento ao cliente" },
      { id: "gl5", texto: "Verificar limpeza e organização" },
      { id: "gl6", texto: "Acompanhar metas de vendas" },
      { id: "gl7", texto: "Verificar reposição de produtos" },
      { id: "gl8", texto: "Conferir sinalização e promoções" },
      { id: "gl9", texto: "Verificar segurança e câmeras" },
      { id: "gl10", texto: "Acompanhar trocas e devoluções" },
      { id: "gl11", texto: "Verificar satisfação do cliente" },
      { id: "gl12", texto: "Analisar produtos mais/menos vendidos" },
      { id: "gl13", texto: "Planejar ações promocionais" },
      { id: "gl14", texto: "Registrar ocorrências do dia" },
    ],
  },
  {
    id: "garantia",
    nome: "Garantia de Peças e Serviços",
    descricao: "Política de garantia",
    icon: "Shield",
    tarefas: [
      { id: "ga1", texto: "Verificar solicitações de garantia pendentes" },
      { id: "ga2", texto: "Analisar laudos técnicos de garantia" },
      { id: "ga3", texto: "Processar devoluções e trocas em garantia" },
    ],
  },
  {
    id: "pagamento",
    nome: "Forma de Pagamento",
    descricao: "Opções de pagamento aceitas",
    icon: "CreditCard",
    tarefas: [
      { id: "pg1", texto: "Verificar funcionamento das máquinas de cartão" },
      { id: "pg2", texto: "Conferir chaves PIX ativas" },
      { id: "pg3", texto: "Verificar condições de parcelamento vigentes" },
    ],
  },
  {
    id: "plano-carreira",
    nome: "Plano de Carreira",
    descricao: "Desenvolvimento e crescimento profissional",
    icon: "TrendingUp",
    tarefas: [
      { id: "pc1", texto: "Avaliar progresso de cada colaborador" },
      { id: "pc2", texto: "Verificar metas de treinamento" },
      { id: "pc3", texto: "Registrar conquistas e certificações" },
      { id: "pc4", texto: "Planejar próximas capacitações" },
      { id: "pc5", texto: "Avaliar promoções e mérito" },
      { id: "pc6", texto: "Acompanhar feedback de clientes por funcionário" },
      { id: "pc7", texto: "Verificar aderência a procedimentos" },
      { id: "pc8", texto: "Registrar advertências e elogios" },
      { id: "pc9", texto: "Definir metas individuais mensais" },
      { id: "pc10", texto: "Fazer avaliação de desempenho" },
      { id: "pc11", texto: "Identificar gaps de competência" },
      { id: "pc12", texto: "Planejar rodízio de funções" },
      { id: "pc13", texto: "Verificar horas de treinamento acumuladas" },
      { id: "pc14", texto: "Acompanhar indicadores de produtividade" },
      { id: "pc15", texto: "Realizar feedbacks semanais" },
      { id: "pc16", texto: "Mapear sucessores para posições-chave" },
      { id: "pc17", texto: "Verificar benefícios e remuneração" },
      { id: "pc18", texto: "Planejar eventos de integração" },
      { id: "pc19", texto: "Acompanhar turnover da equipe" },
      { id: "pc20", texto: "Verificar clima organizacional" },
      { id: "pc21", texto: "Definir PDI (Plano de Desenvolvimento Individual)" },
      { id: "pc22", texto: "Reconhecer destaques do mês" },
      { id: "pc23", texto: "Atualizar organograma" },
      { id: "pc24", texto: "Verificar conformidade trabalhista" },
      { id: "pc25", texto: "Planejar treinamentos externos" },
      { id: "pc26", texto: "Acompanhar cursos em andamento" },
      { id: "pc27", texto: "Verificar prazos de certificações" },
      { id: "pc28", texto: "Registrar feedbacks de clientes" },
      { id: "pc29", texto: "Avaliar engajamento da equipe" },
      { id: "pc30", texto: "Criar relatório mensal de RH" },
    ],
  },
];
