
UPDATE plano_contas SET grupo_dre = '1 - RECEITA BRUTA DE VENDA' WHERE grupo_dre = '1 - Receita bruta de venda';
UPDATE plano_contas SET grupo_dre = '1.1 - VENDA BALCÃO' WHERE grupo_dre = '1.1 - Venda balcão';
UPDATE plano_contas SET grupo_dre = '2.1 - SERVIÇOS TERCEIRIZADOS' WHERE grupo_dre = '2.1 - Serviços terceirizados';
UPDATE plano_contas SET grupo_dre = '3.01 - OUTRAS RECEITAS' WHERE grupo_dre = '3.01 - Outras receitas';
UPDATE plano_contas SET grupo_dre = '4.1 - IMPOSTOS' WHERE grupo_dre = '4.1 - Impostos';
UPDATE plano_contas SET grupo_dre = '4.1.1 - ICMS S/ VENDAS' WHERE grupo_dre = '4.1.1 - ICMS s/ vendas';
UPDATE plano_contas SET grupo_dre = '4.1.2 - IPI S/ VENDAS' WHERE grupo_dre = '4.1.2 - IPI s/ vendas';
UPDATE plano_contas SET grupo_dre = '4.1.3 - PIS S/ VENDAS' WHERE grupo_dre = '4.1.3 - PIS s/ vendas';
UPDATE plano_contas SET grupo_dre = '4.1.4 - COFINS S/ VENDAS' WHERE grupo_dre = '4.1.4 - COFINS s/ vendas';
UPDATE plano_contas SET grupo_dre = '4.3.1 - FRETES E CARRETOS OUTROS SERVIÇO' WHERE grupo_dre = '4.3.1 - Fretes e carretos';
UPDATE plano_contas SET grupo_dre = '4.3.2 - DESPESA C/ COMBUSTÍVEIS VEÍCULOS' WHERE grupo_dre = '4.3.2 - Combustíveis veículos';
UPDATE plano_contas SET grupo_dre = '4.5.1 - COMISSÃO SOBRE A VENDA' WHERE grupo_dre = '4.5.1 - Comissão sobre a venda';
UPDATE plano_contas SET grupo_dre = '4.5.6 - PUBLICIDADE E PROPAGANDA' WHERE grupo_dre = '4.5.6 - Publicidade e propaganda';
UPDATE plano_contas SET grupo_dre = '4.6 - CUSTOS DIRETO OPERACIONAL' WHERE grupo_dre = '4.6 - Custos direto operacional';
UPDATE plano_contas SET grupo_dre = '4.6.2 - EMBALAGENS' WHERE grupo_dre = '4.6.2 - Embalagens';
UPDATE plano_contas SET grupo_dre = '4.6.3 - PRODUTOS QUÍMICOS' WHERE grupo_dre = '4.6.3 - Produtos químicos';
UPDATE plano_contas SET grupo_dre = '4.6.4 - TERCEIRIZAÇÃO DE BALANÇA' WHERE grupo_dre = '4.6.4 - Terceirização de balança';
UPDATE plano_contas SET grupo_dre = '5.1 - PRÓ-LABORE SÓCIOS' WHERE grupo_dre = '5.1 - Pró-labore sócios';
UPDATE plano_contas SET grupo_dre = '5.2.1 - SALÁRIOS OPERACIONAL' WHERE grupo_dre = '5.2.1 - Salários operacional';
UPDATE plano_contas SET grupo_dre = '5.2.17 - GRATIFICAÇÕES DIVERSAS' WHERE grupo_dre = '5.2.17 - Gratificações diversas';
UPDATE plano_contas SET grupo_dre = '5.2.18 - ASSISTÊNCIA MÉDICA E EXAME PERIÓDICO' WHERE grupo_dre = '5.2.18 - Assistência médica';
UPDATE plano_contas SET grupo_dre = '5.2.19 - SINDICATOS E ASSOCIAÇÕES DE CLASSE' WHERE grupo_dre = '5.2.19 - Sindicatos e associações';
UPDATE plano_contas SET grupo_dre = '5.2.20 - ASSISTÊNCIA SOCIAL/CONFRATERNIZAÇÕES' WHERE grupo_dre = '5.2.20 - Assistência social/confraternizações';
UPDATE plano_contas SET grupo_dre = '5.2.21 - AJUDA DE CUSTO' WHERE grupo_dre = '5.2.21 - Ajuda de custo';
UPDATE plano_contas SET grupo_dre = '5.2.22 - CURSOS/TREINAMENTOS/CONGRESSOS' WHERE grupo_dre = '5.2.22 - Cursos/treinamentos/congressos';
UPDATE plano_contas SET grupo_dre = '5.2.5 - 13º SALÁRIO' WHERE grupo_dre = '5.2.5 - 13º salário';
UPDATE plano_contas SET grupo_dre = '5.2.7 - RESCISÕES' WHERE grupo_dre = '5.2.7 - Rescisões';
UPDATE plano_contas SET grupo_dre = '5.2.8 - VALE TRANSPORTE' WHERE grupo_dre = '5.2.8 - Vale transporte';
UPDATE plano_contas SET grupo_dre = '5.2.9 - ALMOÇO / LANCHE / MERCADO' WHERE grupo_dre = '5.2.9 - Almoço/lanche/mercado';
UPDATE plano_contas SET grupo_dre = '5.3.1 - TELEFONE E INTERNET' WHERE grupo_dre = '5.3.1 - Telefone e internet';
UPDATE plano_contas SET grupo_dre = '5.3.3 - ENERGIA ELÉTRICA' WHERE grupo_dre = '5.3.3 - Energia elétrica';
UPDATE plano_contas SET grupo_dre = '5.4.1 - CONTABILIDADE' WHERE grupo_dre = '5.4.1 - Contabilidade';
UPDATE plano_contas SET grupo_dre = '5.4.4 - SISTEMA' WHERE grupo_dre = '5.4.4 - Sistema';
UPDATE plano_contas SET grupo_dre = '5.5.1 - MATERIAIS DE LIMPEZA' WHERE grupo_dre = '5.5.1 - Materiais de limpeza';
UPDATE plano_contas SET grupo_dre = '5.5.3 - MANUTENÇÃO PREDIAL' WHERE grupo_dre = '5.5.3 - Manutenção predial';
UPDATE plano_contas SET grupo_dre = '5.5.4 - MANUTENÇÃO EQUIPAMENTOS' WHERE grupo_dre = '5.5.4 - Manutenção equipamentos';
UPDATE plano_contas SET grupo_dre = '5.6 - DESPESAS ADMINISTRATIVAS' WHERE grupo_dre = '5.6 - Despesas administrativas';
UPDATE plano_contas SET grupo_dre = '5.6.1 - TARIFAS BANCÁRIAS (BB)' WHERE grupo_dre = '5.6.1 - Tarifas bancárias (BB)';
UPDATE plano_contas SET grupo_dre = '5.6.3 - TAXAS PATRONAIS/TFF' WHERE grupo_dre = '5.6.3 - Taxas patronais/TFF';
UPDATE plano_contas SET grupo_dre = '5.6.6 - MATERIAL ESCRITÓRIO E EXPEDIENTE' WHERE grupo_dre = '5.6.6 - Material escritório';
UPDATE plano_contas SET grupo_dre = '6.1 - EMPRÉSTIMOS E APORTES' WHERE grupo_dre = '6.1 - Empréstimos e aportes';
UPDATE plano_contas SET grupo_dre = '7.1 - BANCOS BB (EMPRÉSTIMOS)' WHERE grupo_dre = '7.1 - Bancos (empréstimos)';
UPDATE plano_contas SET grupo_dre = '7.3.1 - MÓVEIS E EQUIPAMENTOS' WHERE grupo_dre = '7.3.1 - Móveis e equipamentos';
UPDATE plano_contas SET grupo_dre = '7.4 - DESPESAS SÓCIO (NENNA)' WHERE grupo_dre = '7.4 - Despesas sócio';
UPDATE plano_contas SET grupo_dre = '7.4.2 - DESPESAS PESSOAL' WHERE grupo_dre = '7.4.2 - Despesas pessoal';
UPDATE plano_contas SET grupo_dre = 'CMV.1 - CUSTO MERCADORIA' WHERE grupo_dre = 'CMV.1 - Custo mercadoria';
