// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrwminvkdcjaqpiptxlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyd21pbnZrZGNqYXFwaXB0eGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMjM1MzEsImV4cCI6MjA4NjU5OTUzMX0.dsB0Y-dYeZvMw3g7pj2kuLe6BHlgyTx54Ib-zRsASlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});